#!/usr/bin/env python3
import argparse
import csv
import json
from datetime import datetime
from pathlib import Path


def parse_float(value, default=0.0):
    try:
        return float(str(value).strip())
    except Exception:
        return default


def parse_int(value, default=0):
    try:
        return int(float(str(value).strip()))
    except Exception:
        return default


def status_for(score):
    if score >= 95:
        return "PASS"
    if score >= 90:
        return "ACCEPTABLE"
    if score >= 75:
        return "DEGRADED"
    return "FAIL"


def read_kpis(path):
    kpis = {}

    with Path(path).open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            keys = list(row.keys())

            name = (
                row.get("kpi")
                or row.get("name")
                or row.get("metric_name")
                or row.get(keys[0])
            )

            value = (
                row.get("value")
                or row.get("mean")
                or row.get("weighted_mean")
                or row.get("weighted_value")
                or row.get(keys[3] if len(keys) > 3 else keys[-1])
            )

            n = (
                row.get("n")
                or row.get("count")
                or row.get("total_n")
                or row.get(keys[-1])
            )

            if not name:
                continue

            kpis[name.strip()] = {
                "value": parse_float(value),
                "n": parse_int(n),
                "raw": row,
            }

    return kpis


def kpi_value(kpis, name, default=0.0):
    return kpis.get(name, {}).get("value", default)


def read_text(path):
    p = Path(path)
    if not p.exists():
        return ""
    return p.read_text(encoding="utf-8", errors="replace")


def weighted_average(items):
    total_weight = sum(weight for _, weight in items)
    if total_weight <= 0:
        return 0.0
    return sum(score * weight for score, weight in items) / total_weight


def main():
    parser = argparse.ArgumentParser(
        description="LoTAF-inspired local trust assessment for Zero-Trust Island Mode."
    )
    parser.add_argument(
        "--kpi",
        default="/mnt/shared/results/integrated_kpi_summary.csv",
        help="KPI summary CSV generated by analyze_integrated_metrics.py",
    )
    parser.add_argument(
        "--audit",
        default="/tmp/island_audit.log",
        help="Island audit log path",
    )
    parser.add_argument(
        "--mesh-trust",
        default="/mnt/shared/island_mode/runtime/mesh_trust_state.json",
        help="Mesh trust state JSON",
    )
    parser.add_argument(
        "--knowledge",
        default="/mnt/shared/island_mode/runtime/outage_knowledge.json",
        help="Outage learning knowledge JSON",
    )
    parser.add_argument(
        "--outdir",
        default="/mnt/shared/results",
        help="Output directory",
    )
    args = parser.parse_args()

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    kpis = read_kpis(args.kpi)
    audit = read_text(args.audit)

    mesh_trust_state = {}
    mesh_trust_path = Path(args.mesh_trust)
    if mesh_trust_path.exists():
        mesh_trust_state = json.loads(mesh_trust_path.read_text())

    outage_knowledge = {}
    knowledge_path = Path(args.knowledge)
    if knowledge_path.exists():
        outage_knowledge = json.loads(knowledge_path.read_text())

    critical_continuity = kpi_value(kpis, "critical_service_continuity")
    unauthorized_blocking = kpi_value(kpis, "unauthorized_access_blocking")
    graceful_degradation = kpi_value(kpis, "island_graceful_degradation")
    trust_aware_mesh = kpi_value(kpis, "trust_aware_mesh_continuity")
    inter_island = kpi_value(kpis, "inter_island_fallback_continuity")
    normal_restore = kpi_value(kpis, "normal_restore_availability")
    policy_correctness = kpi_value(kpis, "overall_policy_correctness")

    evidence = {
        "has_quarantine_event": "quarantine-node" in audit,
        "has_trust_aware_route": "path=ap5->ap3" in audit or "ap5->ap3" in audit,
        "has_inter_island_repair": "inter-island" in audit or "s6-s7-up" in audit,
        "has_policy_cache_event": "compiled-policy-cached" in audit,
        "has_degraded_state": "DEGRADED" in audit,
        "has_islanded_state": "ISLANDED" in audit,
        "current_quarantined_nodes": mesh_trust_state.get("quarantined_nodes", []),
        "learned_paths": sorted(outage_knowledge.get("paths", {}).keys()),
    }

    identity_score = unauthorized_blocking
    policy_score = policy_correctness

    continuity_score = weighted_average([
        (critical_continuity, 0.60),
        (graceful_degradation, 0.20),
        (inter_island, 0.20),
    ])

    mesh_score = trust_aware_mesh
    if not (evidence["has_quarantine_event"] and evidence["has_trust_aware_route"]):
        mesh_score = min(mesh_score, 50.0)

    orchestration_score = weighted_average([
        (normal_restore, 0.50),
        (critical_continuity, 0.30),
        (policy_correctness, 0.20),
    ])

    overall_score = weighted_average([
        (identity_score, 0.25),
        (policy_score, 0.25),
        (continuity_score, 0.20),
        (mesh_score, 0.15),
        (orchestration_score, 0.15),
    ])

    rows = [
        {
            "category": "identity_and_access_control",
            "score_pct": round(identity_score, 2),
            "status": status_for(identity_score),
            "evidence": "unauthorized_access_blocking",
        },
        {
            "category": "policy_enforcement",
            "score_pct": round(policy_score, 2),
            "status": status_for(policy_score),
            "evidence": "overall_policy_correctness",
        },
        {
            "category": "service_continuity_and_degradation",
            "score_pct": round(continuity_score, 2),
            "status": status_for(continuity_score),
            "evidence": "critical_service_continuity + island_graceful_degradation + inter_island_fallback_continuity",
        },
        {
            "category": "mesh_trust_assurance",
            "score_pct": round(mesh_score, 2),
            "status": status_for(mesh_score),
            "evidence": "quarantine event + trust-aware route ap5->ap3 + trust_aware_mesh_continuity",
        },
        {
            "category": "orchestration_and_recovery",
            "score_pct": round(orchestration_score, 2),
            "status": status_for(orchestration_score),
            "evidence": "normal_restore_availability + continuity + policy correctness",
        },
        {
            "category": "overall_local_trust_level",
            "score_pct": round(overall_score, 2),
            "status": status_for(overall_score),
            "evidence": "weighted local trust assessment",
        },
    ]

    summary_path = outdir / "trust_assessment_summary.csv"
    with summary_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["category", "score_pct", "status", "evidence"],
        )
        writer.writeheader()
        writer.writerows(rows)

    report = {
        "generated_at": datetime.utcnow().isoformat(timespec="seconds") + "Z",
        "model": "LoTAF-inspired local trust assessment",
        "scope": "edge-local Zero-Trust Island Mode assessment",
        "source_files": {
            "kpi": str(args.kpi),
            "audit": str(args.audit),
            "mesh_trust": str(args.mesh_trust),
            "outage_knowledge": str(args.knowledge),
        },
        "input_kpis": kpis,
        "evidence": evidence,
        "scores": rows,
        "interpretation": {
            "PASS": "local trust objective satisfied",
            "ACCEPTABLE": "local trust objective mostly satisfied; minor transient effects observed",
            "DEGRADED": "local trust objective partially satisfied",
            "FAIL": "local trust objective not satisfied",
        }
    }

    report_path = outdir / "trust_assessment_report.json"
    report_path.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    print("=== LoTAF-inspired local trust assessment ===")
    for row in rows:
        print(f"{row['category']:<35} {row['score_pct']:>6.2f}% {row['status']}")

    print(f"\n[saved] {summary_path}")
    print(f"[saved] {report_path}")


if __name__ == "__main__":
    main()
